import type { DailyReport } from "./types";

/**
 * Formats a number as Indian currency string (no symbol).
 */
function fmt(n: number): string {
  return n.toLocaleString("en-IN");
}

/**
 * Builds a WhatsApp-ready text message for a daily report.
 */
export function buildDailyReportWhatsAppMessage(report: DailyReport): string {
  const dateLabel = new Date(report.date).toLocaleDateString("en-IN", {
    weekday: "long",
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const profitSign = report.netProfit >= 0 ? "+" : "";
  const profitEmoji = report.netProfit >= 0 ? "📈" : "📉";

  const lines = [
    `📊 *Daily Closing Report*`,
    ``,
    `🏪 *Shop:* ${report.shopName}`,
    `📅 *Date:* ${dateLabel}`,
    ``,
    `━━━━━━━━━━━━━━━━━━━`,
    `💰 *Sales Summary*`,
    `• Total Sales: ₹${fmt(report.totalSales)}`,
    `• Cash: ₹${fmt(report.cashSales)}  |  UPI: ₹${fmt(report.upiSales)}`,
    `• Transactions: ${report.salesCount}`,
    ``,
    `💸 *Expenses*`,
    `• Total Expenses: ₹${fmt(report.totalExpenses)}`,
    ``,
    `${profitEmoji} *Net Profit: ${profitSign}₹${fmt(report.netProfit)}* (${profitSign}${report.profitMarginPercent}%)`,
    ``,
    `━━━━━━━━━━━━━━━━━━━`,
    `🧾 *Due Summary*`,
    `• Due Added: ₹${fmt(report.dueAdded)}`,
    `• Collections: ₹${fmt(report.dueCollected)}`,
    `• Pending Balance: ₹${fmt(report.pendingDueBalance)}`,
    ``,
    `━━━━━━━━━━━━━━━━━━━`,
    `📌 *Performance*`,
    `• Customers: ${report.uniqueCustomersCount}`,
    `• Avg Sale: ₹${fmt(Math.round(report.averageSaleValue))}`,
    ``,
    `_Generated by Drakvex One_`,
  ];

  return lines.join("\n");
}

/**
 * Opens WhatsApp with the pre-filled report message.
 */
export function shareReportOnWhatsApp(report: DailyReport): void {
  const message = buildDailyReportWhatsAppMessage(report);
  const encoded = encodeURIComponent(message);
  const url = `https://wa.me/?text=${encoded}`;
  window.open(url, "_blank", "noopener,noreferrer");
}
